### ISSUE TITLE
How to read posts?

### ISSUE THREAD

**Issue by makorne** [FedericoBruzzone/tgt#33]
1) Wow!! I've started tgt!! Great! Colorfull!

But how to read posts? 
Here I have 1 chat but cant use any buttons or mouse to read posts.

2) The example telegram shows only prompt :
`
Enter command (gcs - GetChats, gc <chatId> - GetChat, me - GetMe, sm <chatId> <message> - SendMessage, lo - LogOut, q - Quit, mcl - MainChatList, h <chatId> - GetChatHistory): 
`
And it doesn`t show the chat,  no commands show the chat altough this is the same account as in tgt.
Even if I use this chatId in gc command

**Comment by FedericoBruzzone** [comment]
Thank you again for your contribution @makorne !

1. We are very glad you like it, if you look here (https://github.com/FedericoBruzzone/tgt/blob/main/docs/configuration/theme.toml.md) you can customize the theme as you like!!😊

2. ‼️All the examples I advise you not to use them‼️
While regarding `tgt` for the moment the mouse is not supported but all keybindings can be found here (https://github.com/FedericoBruzzone/tgt/blob/main/docs/configuration/keymap.toml.md).


Anyway, to select a chat to see messages you can do:

```
alt+1
```

Then use the arrows to select the chat and press `enter` to open it.


P.S. in general, all the documentation can be found here: https://github.com/FedericoBruzzone/tgt/tree/main/docs/configuration


Translated with DeepL (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation)

**Comment by makorne** [comment]
Very strange default key binding for TUI.
Why not use the usual keys: up-down arrows and enter? 
Why the way it is in mc, fc - possible most used TUI apps?

Alt-1 switch me to first tab in terminal and looks like this is the default binding in most linux terminals.
So users can`t even select a chat without changing default key binding.

**Comment by FedericoBruzzone** [comment]
Thanks again for your feedback! Any other strange things you find let us know, your help is important!

I used konsole and now kitty and as defaul "meta" key i dictated the "win" key.

However we were holding "alt+1" or "alt+left" because when you are inside the prompt you can switch to the chat_list without pressing "esc." Because the "left" and "right" keys when the prompt is focused are used to move through the text.

However, this is not an official release. 
We will plan to add this default key bindings!

Anyway you can add inside ".config/tgt/keymap.toml" your favorite keybindings for now! 😊
