### ISSUE TITLE
[bug]: Login fails with API_ID_PUBLISHED_FLOOD

### ISSUE THREAD

**Issue by Nugumanov** [FedericoBruzzone/tgt#63]
### Describe the bug

Cannot login, receiving API_ID_PUBLISHED_FLOOD. Tried both 7 and +7 regions in phone number.

### Reproduction steps

1. Run tgt
2. Enter phone number
3. Press enter

### Expected behavior

App accepts a phone number and proceeds to authorization.

### Logs and screenshots

Enter your phone number (include the country calling code):
7XXXXXXXXX1
API_ID_PUBLISHED_FLOOD
Enter your phone number (include the country calling code):

### Method of Installation

Cargo

### tgt version

1.0.0

### Operating System (including version and architecture)

MacOS Sonoma 14.2.1 (23C71)

### Terminal and Command Line Interface (CLI) (including versions)

kitty 0.31.0 created by Kovid Goyal

### rustc and rustup target (including versions)

rustc 1.80.1 (3f5fd8dd4 2024-08-06)

**Comment by FedericoBruzzone** [comment]
The API_ID_PUBLISHED_FLOOD error indicates that Telegram's API has flagged our API ID due to flood prevention. This usually happens when:
1. There have been too many login attempts in a short time, triggering a rate limit.
2. Our API ID has been exposed to all tgt users, causing Telegram to flag it for security reasons.

### How to resolve the issue:
Visit [Telegram's API page](https://my.telegram.org/) to generate new credentials and replace the affected ones in `~/.tgt/config/telegram.toml`.
```toml
api_id = "94575"
#         ^^^^^__ To replace
api_hash = "a3406de8d171bb422bb6ddf3bbd800e2"
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^__ To replace
```

Related Issues:
1. https://github.com/tdlib/td/issues/2722
2. https://github.com/NixOS/nixpkgs/issues/55271
